### ISSUE TITLE
excuse me? is there any doc for this?

### ISSUE THREAD

**Issue by imgbed** [3bl3gamer/tgclient#1]
i find this project is the latest update , i think it will be the newest that can be really useful. but i can't use it with less document.

**Comment by 3bl3gamer** [comment]
Hello. No, there are no docs yet. I gonna write it later but for now I'll leave here brief description.

You may use my another repo as an example, in particular his file: https://github.com/3bl3gamer/tg-history-dumper/blob/master/tg.go#L89

## Create

First, `TGClient` object should be created with `tgclient.NewTGClient` or `tgclient.NewTGClientExt` for example:

```go
tg := tgclient.NewTGClient(appID, appHash, &mtproto.SimpleLogHandler{})
```
And if you need more customization:

```go
// Telegram client info
cfg := &mtproto.AppConfig{
    AppID:          appID,
    AppHash:        appHash,
    AppVersion:     "0.0.1",
    DeviceModel:    "Unknown",
    SystemVersion:  runtime.GOOS + "/" + runtime.GOARCH,
    SystemLangCode: "en",
    LangPack:       "",
    LangCode:       "en",
}

// store stat will save/read session data
sessStore := &mtproto.SessFileStore{FPath: "tg_session.json"}

// optional dialer (may be nil) for proxying requests
dialer, err := proxy.SOCKS5("tcp", "127.0.0.1:9050", nil, proxy.Direct)

tg := tgclient.NewTGClientExt(cfg, sessStore, logHandler, dialer)
```

## Connect

Then, connection should be opened:

```go
err := tg.InitAndConnect()
```

## Auth

And client should authenticate with `AuthAndInitEvents` or `AuthExt`, for example:

```go
// object that will... provide auth data:
// phone number, confirmation code and optionally password.
// ScanfAuthDataProvider will just prompt all this from terminal.
authDataProvider := mtproto.ScanfAuthDataProvider{}

err := tgclient.AuthAndInitEvents(authDataProvider)
```

While authing, `AuthAndInitEvents` sends `mtproto.TL_updates_getState` request. It makes TG server send updates to client (like new incoming messages). If you do not need those (maybe you just want to dump your chats history), you may send something different:

```go
authDataProvider := mtproto.ScanfAuthDataProvider{}
payload := mtproto.TL_users_getUsers{ID: []mtproto.TL{mtproto.TL_inputUserSelf{}}}

resp, err := tg.AuthExt(authDataProvider, payload)
// here resp should be a mtproto.VectorObject with one mtproto.TL_user item.
```

## Communicate

With `tg.SendSync` or `tg.SendSyncRetry`. First one just sends request and returns response whatever it will be, so you generally should check if you got what you expected. For example:

```go
res := c.tg.SendSync(mtproto.TL_contacts_resolveUsername{Username: "some chat name"})
peer, ok := res.(mtproto.TL_contacts_resolvedPeer)
if !ok {
  // res will likely be TL_rpc_error with message USERNAME_NOT_OCCUPIED or RPC_CALL_FAIL or other
  return mtproto.WrongRespError(res)
}
for _, chat := range peer.Chats {
    fmt.Printf("%#v\n", chat)
}
```

Often you will receive temporary errors like `RPC_CALL_FAIL` of `FOOLD_WAIT_123` and want to re-send same request after little delay. This is done by
```go
res := tg.SendSyncRetry(request, time.Second, 0, 30*time.Second)
```

## Updates

Pass callback func:

```go
tg.SetUpdateHandler(func(updateTL mtproto.TL) {
    switch update := updateTL.(type) {
        case mtproto.TL_updateUserStatus:
            fmt.Printf("U#%d %T\n", update.UserID, update.Status)
        case mtproto.TL_updateNewChannelMessage:
            ...
        case mtproto.TL_updateEditChannelMessage:
            ...
        ...
        default:
            return mtproto.WrongRespError(updateTL)
        }
    }
})
```

**Comment by 3bl3gamer** [comment]
Sent it all to [README.md](https://github.com/3bl3gamer/tgclient/blob/master/README.md).
