### ISSUE TITLE
The downloader error causes the program to crash

### ISSUE THREAD

**Issue by wind-hx** [3bl3gamer/tgclient#11]
<img width="824" alt="截屏2022-06-26 18 08 31" src="https://user-images.githubusercontent.com/17685971/175809400-57d7ac57-488b-42c0-bbbe-e805e18c0155.png">

**Comment by 3bl3gamer** [comment]
That channel may be closed if the `tgclient.Disconnect()` was called a second time without connecting (`tgclient.InitAndConnect()`). Was it so?

**Comment by wind-hx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
