### ISSUE TITLE
Wrong bits of message_id: 0

### ISSUE THREAD

**Issue by wind-hx** [3bl3gamer/tgclient#12]
[ERROR] failed to connect:
Wrong bits of message_id: 0

wind.com/telegram-transport/src/tgclient/mtproto.(*MTProto).read
        /Users/wind/project/go-project/telegram-transport-go/src/tgclient/mtproto/network.go:193
wind.com/telegram-transport/src/tgclient/mtproto.(*MTProto).makeAuthKey
        /Users/wind/project/go-project/telegram-transport-go/src/tgclient/mtproto/network.go:213
wind.com/telegram-transport/src/tgclient/mtproto.(*MTProto).initConection
        /Users/wind/project/go-project/telegram-transport-go/src/tgclient/mtproto/mtproto.go:248
wind.com/telegram-transport/src/tgclient/mtproto.(*MTProto).Connect
        /Users/wind/project/go-project/telegram-transport-go/src/tgclient/mtproto/mtproto.go:297
wind.com/telegram-transport/src/tgclient/mtproto.(*MTProto).InitSessAndConnect
        /Users/wind/project/go-project/telegram-transport-go/src/tgclient/mtproto/mtproto.go:179
wind.com/telegram-transport/src/tgclient.(*TGClient).InitAndConnect
        /Users/wind/project/go-project/telegram-transport-go/src/tgclient/tgclient.go:76
wind.com/telegram-transport/src/mtproto.TInit
        /Users/wind/project/go-project/telegram-transport-go/src/mtproto/api.go:82
wind.com/telegram-transport/src/mtproto.TSendCode
        /Users/wind/project/go-project/telegram-transport-go/src/mtproto/api.go:260
wind.com/telegram-transport/src/service.SendCode
        /Users/wind/project/go-project/telegram-transport-go/src/service/client.go:62
wind.com/telegram-transport/src/controller.SendCode
        /Users/wind/project/go-project/telegram-transport-go/src/controller/client.go:123
github.com/gin-gonic/gin.(*Context).Next
        /Users/wind/project/go-project/telegram-transport-go/vendor/github.com/gin-gonic/gin/context.go:168
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
        /Users/wind/project/go-project/telegram-transport-go/vendor/github.com/gin-gonic/gin/recovery.go:99
github.com/gin-gonic/gin.(*Context).Next
        /Users/wind/project/go-project/telegram-transport-go/vendor/github.com/gin-gonic/gin/context.go:168
github.com/gin-gonic/gin.LoggerWithConfig.func1
        /Users/wind/project/go-project/telegram-transport-go/vendor/github.com/gin-gonic/gin/logger.go:241
github.com/gin-gonic/gin.(*Context).Next
        /Users/wind/project/go-project/telegram-transport-go/vendor/github.com/gin-gonic/gin/context.go:168
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
        /Users/wind/project/go-project/telegram-transport-go/vendor/github.com/gin-gonic/gin/gin.go:555
github.com/gin-gonic/gin.(*Engine).ServeHTTP
        /Users/wind/project/go-project/telegram-transport-go/vendor/github.com/gin-gonic/gin/gin.go:511
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2879
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1930
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1581

**Comment by 3bl3gamer** [comment]
How often does it happen? Can you reproduce this error?

**Comment by wind-hx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wind-hx** [comment]
Sorry because I changed some code of the tgclient project
