### ISSUE TITLE
A proposal for the ObjectGenerated method

### ISSUE THREAD

**Issue by wind-hx** [3bl3gamer/tgclient#30]
tl_schema.go, There are too many cases in the ObjectGenerated function. It is recommended to wrap each case into a function.
CPU consumption is very high due to frequent and large ObjectGenerated functions.

**Comment by 3bl3gamer** [comment]
Thank you for suggestion!

I have prepared two buffers with encoded TL objects:
 * large: ~100KB `TL_messages_channelMessages` with one message with embedded Instant View page,
 * tiny: four-byte `TL_starsTransactionPeerAds` (which has no fields at all).

I used these buffers to benchmark three versions of `ObjectGenerated`:
1) single large `switch` (current one),
2) single switch where each case is a single function call:
 ```go
 case CRC_inputMediaPoll:
	r = decode_TL_inputMediaPoll(m)
case CRC_inputMediaDice:
	r = decode_TL_inputMediaDice(m)
```
3) map of functions from (2):
```go
decodeFuncsMap = map[uint32]func(*DecodeBuf) TL{
	CRC_messageMediaPoll:  decode_TL_messageMediaPoll,
	CRC_messageMediaDice:  decode_TL_messageMediaDice,
	CRC_messageMediaStory: decode_TL_messageMediaStory,
```

Run each one with `GOMAXPROCS=1 go test -bench=. -benchtime=10s`. Results:

```
switch (current)
BenchmarkDecodeLarge 	   23508	    511975 ns/op
BenchmarkDecodeTiny  	1000000000	         7.082 ns/op

switch + funcs
BenchmarkDecodeLarge 	   24606	    490263 ns/op
BenchmarkDecodeSmall 	1000000000	         6.847 ns/op

map + funcs
BenchmarkDecodeLarge 	   23624	    506770 ns/op
BenchmarkDecodeTiny  	407025956	        29.50 ns/op
```

Last (map + funcs) also produces one extra allocation per run (according to `-benchmem`), but I'm not sure what is the cause.

Did you describe the second (switch + funcs) version? It seems to be the fastest one, but why? Is it related to some Go-specific optimizations, or maybe short jumps or something else?

**Comment by wind-hx** [comment]
(map + funcs) The solution is to ask chatgpt, which gives the optimization direction.
In the production environment, my cpu is full, so I am looking for a solution to optimize cpu usage. If I can't find it, I can only upgrade the server configuration.


<img width="1248" alt="image" src="https://github.com/user-attachments/assets/6b063395-fd11-424d-96b6-dcee527b466f">
<img width="855" alt="image" src="https://github.com/user-attachments/assets/c497b3be-8020-4dd2-816e-22877bbc2bb5">
[pprof.telegram-transport.samples.cpu.005.pb.gz](https://github.com/user-attachments/files/16956078/pprof.telegram-transport.samples.cpu.005.pb.gz)

**Comment by 3bl3gamer** [comment]
I've optimized the decoder a bit (got rid of some excess buffers copying and interface conversions). Object decoding is now ~20% faster according to benchmarks. Will it help?

I've also added a "regualr" benchmark case: a 100-byte buffer with a `TL_messages_channelMessages{}` response with a simple short plain text message (message itself is ~20 bytes but there is also a sender's info).

Switch+funcs is still faster than map+funcs so I'm keeping the first one.

```
v0.186.1
Large       884349 ns/op      465960 B/op       12844 allocs/op
Regular       1876 ns/op        1392 B/op          28 allocs/op
Tiny             8.231 ns/op       0 B/op           0 allocs/op

v0.186.1 + map insted of switch
Large       936009 ns/op      466024 B/op       12845 allocs/op
Regular       1961 ns/op        1456 B/op          29 allocs/op
Tiny            57.84 ns/op       64 B/op           1 allocs/op

v0.186.0
Large      1160268 ns/op      518128 B/op       16695 allocs/op
Regular       2316 ns/op        1544 B/op          34 allocs/op
Tiny            15.74 ns/op        0 B/op           0 allocs/op
```

These were run with `GOMAXPROCS=1 go test -bench=. -benchtime=5s -benchmem`.

**Comment by wind-hx** [comment]
Awesome, this adjustment is very useful
