### ISSUE TITLE
telegram error SESSION_REVOKED

### ISSUE THREAD

**Issue by wind-hx** [3bl3gamer/tgclient#5]
For some accounts, "SESSION_REVOKED" will appear within 30 minutes of logging in, and you need to log in again.

**Comment by 3bl3gamer** [comment]
Were those accounts logged in via `tgclient` only? If not, have they been logged out from other clients too?

How long ago these accounts were created?

**Comment by wind-hx** [comment]
The test found that the app_id and app_hash of telegram caused the error
